package com.agentapi.exception;

public enum ErrorCode {

    INVALID_REQUEST,
    ASSISTANT_NOT_FOUND,
    LLM_UNAVAILABLE,
    MODEL_NOT_FOUND,
    LLM_TIMEOUT,
    LLM_COMMUNICATION_ERROR,
    TOOL_NOT_FOUND,
    TOOL_NOT_ALLOWED,
    TOOL_EXECUTION_ERROR,
    INTERNAL_ERROR
}
