package com.agentapi.exception;

public enum ErrorCode {

    INVALID_REQUEST,
    ASSISTANT_NOT_FOUND,
    LLM_UNAVAILABLE,
    MODEL_NOT_FOUND,
    LLM_TIMEOUT,
    LLM_COMMUNICATION_ERROR,
    TOOL_NOT_FOUND,
    TOOL_NOT_ALLOWED,
    TOOL_EXECUTION_ERROR,
    RAG_DOCUMENT_NOT_FOUND,
    INTERNAL_ERROR,
    UNAUTHORIZED,
    CONNECTION_REQUIRED,
    CONNECTION_NOT_FOUND,
    PROJECT_NOT_FOUND,
    PROJECT_NOT_ALLOWED,
    AGENT_NOT_FOUND,
    AGENT_NOT_ALLOWED,
    SESSION_NOT_FOUND,
    SESSION_NOT_RUNNING,
    AGENT_START_FAILED,
    AGENT_TIMEOUT,
    AGENT_ERROR,
    INVALID_CREDENTIALS
}
